name = "ApproxOperator"
uuid = "6dcad7c1-d118-4fbd-9616-5407c5210a62"
authors = ["jcwu <jcwu@hqu.edu.cn> and contributors"]
version = "0.1.0"

[deps]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
Revise = "3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
